/**
 * 
 */
package com.mastermind.util;

import java.util.Calendar;

/**
 * @author Alan Ly
 *
 */
public class ConsoleUtilities {
    
    /**
     * Generates an appropriate time stamp for insertion into status messages. This method returns the current date and time in a string.
     * 
     * An example of the timestamp generated by this code is,
     * <blockquote>
     * 29/05/2010 22:07:34
     * </blockquote>
     * @return the current date and time in a string
     */
    public static String generateTimeStamp() {
	Calendar calendar = Calendar.getInstance();
	
	return calendar.get(Calendar.DAY_OF_MONTH) + "/" + (calendar.get(Calendar.MONTH) + 1) 
	+ "/" + calendar.get(Calendar.YEAR) + " " + calendar.get(Calendar.HOUR_OF_DAY) + ":" 
	+ calendar.get(Calendar.MINUTE) + ":" + calendar.get(Calendar.SECOND);
    }
    
}
